2019-07-20 13:53:16,495 ERROR: Exception on /test [POST] [in d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Preston\Documents\PythonProjects\Web Development\Flask_capstone\app\routes.py", line 18, in test
    if form.validate_on_submit():
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\fields\core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\fields\core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\validators.py", line 273, in __call__
    match = self.regex.match(field.data or '')
TypeError: expected string or bytes-like object
2019-07-20 13:53:19,508 ERROR: Exception on /test [POST] [in d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Preston\Documents\PythonProjects\Web Development\Flask_capstone\app\routes.py", line 18, in test
    if form.validate_on_submit():
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\fields\core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\fields\core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\validators.py", line 273, in __call__
    match = self.regex.match(field.data or '')
TypeError: expected string or bytes-like object
2019-07-20 13:53:30,437 ERROR: Exception on /test [POST] [in d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Preston\Documents\PythonProjects\Web Development\Flask_capstone\app\routes.py", line 18, in test
    if form.validate_on_submit():
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\fields\core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\fields\core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "d:\preston\documents\pythonprojects\web development\flask_capstone\venv\lib\site-packages\wtforms\validators.py", line 273, in __call__
    match = self.regex.match(field.data or '')
TypeError: expected string or bytes-like object
